name: locacharge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  geolocator: ^9.0.2
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.3.0 # Updated to latest stable version
  timezone: ^0.10.0 # Updated to be compatible with flutter_local_notifications 19.3.0

  # Firebase
  firebase_core: ^2.27.0 # Veuillez vérifier la dernière version sur pub.dev
  firebase_auth: ^4.17.8 # Veuillez vérifier la dernière version sur pub.dev
  cloud_firestore: ^4.15.8 # Veuillez vérifier la dernière version sur pub.dev


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # fonts:
  # - family: Inter
  #   fonts:
  #     - asset: assets/fonts/Inter-Regular.ttf
  #     - asset: assets/fonts/Inter-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Inter-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Inter-Bold.ttf
  #       weight: 700
