// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAINm9WunfrRK-tjvG4pRI9c_BK9wwyFWU',
    appId: '1:170207846950:web:f4f9f632ace81476e23ce7',
    messagingSenderId: '170207846950',
    projectId: 'moneycharge-ebf19',
    authDomain: 'moneycharge-ebf19.firebaseapp.com',
    storageBucket: 'moneycharge-ebf19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLUw-PfRmUmRrEnlp9RSaAzWuY5ZgdEps',
    appId: '1:170207846950:android:ced6ea4908aa34dae23ce7',
    messagingSenderId: '170207846950',
    projectId: 'moneycharge-ebf19',
    storageBucket: 'moneycharge-ebf19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrWJSUGSWEIXE3KS78uHqRUp_hgYY5-p8',
    appId: '1:170207846950:ios:b9fa085b234966b6e23ce7',
    messagingSenderId: '170207846950',
    projectId: 'moneycharge-ebf19',
    storageBucket: 'moneycharge-ebf19.firebasestorage.app',
    iosBundleId: 'com.example.locacharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrWJSUGSWEIXE3KS78uHqRUp_hgYY5-p8',
    appId: '1:170207846950:ios:b9fa085b234966b6e23ce7',
    messagingSenderId: '170207846950',
    projectId: 'moneycharge-ebf19',
    storageBucket: 'moneycharge-ebf19.firebasestorage.app',
    iosBundleId: 'com.example.locacharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAINm9WunfrRK-tjvG4pRI9c_BK9wwyFWU',
    appId: '1:170207846950:web:31abcb78a5e54efde23ce7',
    messagingSenderId: '170207846950',
    projectId: 'moneycharge-ebf19',
    authDomain: 'moneycharge-ebf19.firebaseapp.com',
    storageBucket: 'moneycharge-ebf19.firebasestorage.app',
  );

}